name: Build EXE

on:
  push:
    tags:
      - 'v*' # Срабатывает при пуше тега, например v1.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install colorama pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --uac-admin --name "WAC_System_Control" main.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: dist/WAC_System_Control.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
